name: Fetch Code Scanning Results
 
on:
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab
 
jobs:
  fetch-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
 
      - name: Install dependencies
        run: pip install requests
 
      - name: Run script to fetch code scanning results
        env:
          TOKEN: ${{ secrets.TOKEN}}
        run: python codescanning.py
 
      - name: Commit and push JSON file
        run: |
          git config --global user.name 'Gee-tha-S'
          git config --global user.email 'github-actions[bot]@users.geethasrinivasan2000@gmail.com'
          git add code-scanning-alerts.json
          git commit -m 'Add generated code-scanning-alerts.json'
          git push
        env:
          TOKEN: ${{ secrets.TOKEN}}
      
